#ifndef MACROS_H
#define MACROS_H

    #define RutaEM1CW parsePtr->mapaChar["RutaEM1CW"]
    #define RutaEM2CW parsePtr->mapaChar["RutaEM2CW"]
    #define RutaEM1ML parsePtr->mapaChar["RutaEM1ML"]
    #define RutaEM2ML parsePtr->mapaChar["RutaEM2ML"]
    #define RutaIteracionesEM1 parsePtr->mapaChar["RutaIteracionesEM1"]
    #define RutaIteracionesEM2 parsePtr->mapaChar["RutaIteracionesEM2"]
    #define RutaIterMax parsePtr->mapaChar["RutaIterMax"]
    #define EM1CW parsePtr->mapaBool["EM1CW"]
    #define EM2CW parsePtr->mapaBool["EM2CW"]
    #define EM1ML parsePtr->mapaBool["EM1ML"]
    #define EM2ML parsePtr->mapaBool["EM2ML"]
    #define termico parsePtr->mapaBool["termico"]
    #define guardaSpotsIter parsePtr->mapaBool["guardaSpotsIter"]
    #define guardaIterMax parsePtr->mapaBool["guardaIterMax"]
    #define numeroLaminas parsePtr->mapaEnteros["numeroLaminas"]
    #define iteraciones parsePtr->mapaEnteros["iteraciones"]
    #define NTerm parsePtr->mapaEnteros["NTerm"]
    #define L1 parsePtr->mapaDobles["L1"]
    #define L2 parsePtr->mapaDobles["L2"]
    #define L parsePtr->mapaDobles["L"]
    #define n parsePtr->mapaDobles["n"]
    #define f1 parsePtr->mapaDobles["f1"]
    #define f2 parsePtr->mapaDobles["f2"]
    #define lambda parsePtr->mapaDobles["lambda"]
    #define PLaser parsePtr->mapaDobles["PLaser"]
    #define umbral parsePtr->mapaDobles["umbral"]
    #define ladoX parsePtr->mapaDobles["ladoX"]
    #define ladoY parsePtr->mapaDobles["ladoY"]
    #define alpha parsePtr->mapaDobles["alpha"]
    #define n2 parsePtr->mapaDobles["n2"]
    #define nPump parsePtr->mapaDobles["nPump"]
    #define kth parsePtr->mapaDobles["kth"]
    #define chi parsePtr->mapaDobles["chi"]
    #define Cp parsePtr->mapaDobles["Cp"]
    #define rho parsePtr->mapaDobles["rho"]
    #define dn_dT parsePtr->mapaDobles["dn_Dt"]
    #define wPumpTan parsePtr->mapaDobles["wPumpTan"]
    #define wPumpSag parsePtr->mapaDobles["wPumpSag"]
    #define divPump parsePtr->mapaDobles["divPump"]
    #define lambdaPump parsePtr->mapaDobles["lambdaPump"]
    #define PPump parsePtr->mapaDobles["PPump"]
    #define RA parsePtr->mapaDobles["RA"]
    #define RB parsePtr->mapaDobles["RB"]
    #define tLente parsePtr->mapaDobles["tLente"]
    #define nLente parsePtr->mapaDobles["nLente"]
    #define inclinacionLente parsePtr->mapaDobles["inclinacionLente"]
    #define tEspejo parsePtr->mapaDobles["tEspejo"]
    #define nEspejo parsePtr->mapaDobles["nEspejo"]
    #define separacionFuenteALente parsePtr->mapaDobles["separacionFuenteALente"]
    #define separacionLenteAEspejo parsePtr->mapaDobles["separacionLenteAEspejo"]


#endif // MACROS_H
